### ISSUE TITLE
phpunit failure with privacy provider 

### ISSUE THREAD

**Issue by mnods** [JosePFs/moodle-filter_tabs#13]
Hi, thanks for this plugin, just reporting this in case you weren't aware. cheers

mdl 3.9.x

10:11:16.409 3) provider_testcase::test_all_providers_compliant with data set "filter_tabs" ('filter_tabs', 'filter_tabs\privacy\provider')
10:11:16.409 Failed asserting that false is true.
10:11:16.409 
10:11:16.409 /opt/data/go-agent/pipelines/Moodle/moodle/privacy/tests/provider_test.php:178
10:11:16.409 /opt/data/go-agent/pipelines/Moodle/moodle/lib/phpunit/classes/advanced_testcase.php:80
10:11:16.409

**Comment by JosePFs** [comment]
Hello,
Thank you very much, I haven't reviewed the plugin for a long time!
