### ISSUE TITLE
Bookmodule only prints the content on the first tab

### ISSUE THREAD

**Issue by stempvoort** [JosePFs/moodle-filter_tabs#9]
Hi, We love the tab option to organise our content.
We use it a lot in the bookmodule. 
We encounter a problem with the printing options of the bookmodule. When printing a page/chapter only the content of the tab shown is printed. 
That's not a big problem, one just has to give a print order for every tab content which has to be printed. But with the "print whole bookmodule" option it is it is a real problem that only the tabs shown are printed
Could this be solved or is there a workaround?

Thanks very much for your help,

Willem

**Comment by stempvoort** [comment]
Hi,
Any suggestion would be welcome...
TIA
Willem

**Comment by JosePFs** [comment]
Hi!
Sorry for taking so long to answer
I am updating the plugin and it will be available as soon as possible.

By the way, what version are you using?

**Comment by stempvoort** [comment]
HoI José,

  Thank you for working on a solution! we have v 3.5 but are planning an 
update soon

greetings,
met vriendelijke groet,


Willem van Stempvoort


Op 20-8-2019 om 22:59 schreef José Puente:

**Comment by JosePFs** [comment]
> met vriendelijke groet,

Hi stempvoort!

I have uploaded the corrections so that the print is displayed correctly.
If you detect any problem I will thank you for the feedback.

Un saludo!
